Measure.wine.origin=Measure(wine,wine,target="Class")
Measure.wine.3.smote=Measure(smote.wine.3,wine,target="Class")
Measure.wine.3.ROSE=Measure(rose.wine.3,wine,target="Class")
Measure.wine.3.GANs=Measure(GANs.wine.3,wine,target="Class")
Measure.wine.3.auto=Measure(auto.wine.3,wine,target="Class")
Measure.wine.origin$records
Measure.wine.3.smote$records
Measure.wine.3.ROSE$records
Measure.wine.3.GANs$records
Measure.wine.3.auto$records
Measure.banking.origin=Measure(banking,banking,target="Class")
Measure.banking.3.smote=Measure(smote.banking.3,banking,target="Class")
Measure.banking.3.ROSE=Measure(rose.banking.3,banking,target="Class")
Measure.banking.3.GANs=Measure(GANs.banking.3,banking,target="Class")
Measure.banking.3.auto=Measure(auto.banking.3,banking,target="Class")
Measure.banking.origin$records
Measure.banking.3.smote$records
Measure.banking.3.ROSE$records
Measure.banking.3.GANs$records
Measure.banking.3.auto$records
Measure.abalone.origin=Measure(abalone,abalone,target="Class")
Measure.abalone.3.smote=Measure(smote.abalone.3,abalone,target="Class")
Measure.abalone.3.ROSE=Measure(rose.abalone.3,abalone,target="Class")
Measure.abalone.3.GANs=Measure(GANs.abalone.3,abalone,target="Class")
Measure.abalone.3.auto=Measure(auto.abalone.3,abalone,target="Class")
Measure.abalone.origin$records
Measure.abalone.3.smote$records
Measure.abalone.3.ROSE$records
Measure.abalone.3.GANs$records
Measure.abalone.3.auto$records
Measure.Caravan.origin=Measure(Caravan,Caravan,target="Class")
Measure.Caravan.3.smote=Measure(smote.Caravan.3,Caravan,target="Class")
Measure.Caravan.3.ROSE=Measure(rose.Caravan.3,Caravan,target="Class")
Measure.Caravan.3.GANs=Measure(GANs.Caravan.3,Caravan,target="Class")
Measure.Caravan.3.auto=Measure(auto.Caravan.3,Caravan,target="Class")
Measure.Caravan.origin$records
Measure.Caravan.3.smote$records
Measure.Caravan.3.ROSE$records
Measure.Caravan.3.GANs$records
Measure.Caravan.3.auto$records

Measure.wine.origin=Measure(wine,wine,target="Class")
Measure.wine.5.smote=Measure(smote.wine.5,wine,target="Class")
Measure.wine.5.ROSE=Measure(rose.wine.5,wine,target="Class")
Measure.wine.5.GANs=Measure(GANs.wine.5,wine,target="Class")
Measure.wine.5.auto=Measure(auto.wine.5,wine,target="Class")
Measure.wine.origin$records
Measure.wine.5.smote$records
Measure.wine.5.ROSE$records
Measure.wine.5.GANs$records
Measure.wine.5.auto$records
Measure.banking.origin=Measure(banking,banking,target="Class")
Measure.banking.5.smote=Measure(smote.banking.5,banking,target="Class")
Measure.banking.5.ROSE=Measure(rose.banking.5,banking,target="Class")
Measure.banking.5.GANs=Measure(GANs.banking.5,banking,target="Class")
Measure.banking.5.auto=Measure(auto.banking.5,banking,target="Class")
Measure.banking.origin$records
Measure.banking.5.smote$records
Measure.banking.5.ROSE$records
Measure.banking.5.GANs$records
Measure.banking.5.auto$records
Measure.abalone.origin=Measure(abalone,abalone,target="Class")
Measure.abalone.5.smote=Measure(smote.abalone.5,abalone,target="Class")
Measure.abalone.5.ROSE=Measure(rose.abalone.5,abalone,target="Class")
Measure.abalone.5.GANs=Measure(GANs.abalone.5,abalone,target="Class")
Measure.abalone.5.auto=Measure(auto.abalone.5,abalone,target="Class")
Measure.abalone.origin$records
Measure.abalone.5.smote$records
Measure.abalone.5.ROSE$records
Measure.abalone.5.GANs$records
Measure.abalone.5.auto$records
Measure.Caravan.origin=Measure(Caravan,Caravan,target="Class")
Measure.Caravan.5.smote=Measure(smote.Caravan.5,Caravan,target="Class")
Measure.Caravan.5.ROSE=Measure(rose.Caravan.5,Caravan,target="Class")
Measure.Caravan.5.GANs=Measure(GANs.Caravan.5,Caravan,target="Class")
Measure.Caravan.5.auto=Measure(auto.Caravan.5,Caravan,target="Class")
Measure.Caravan.origin$records
Measure.Caravan.5.smote$records
Measure.Caravan.5.ROSE$records
Measure.Caravan.5.GANs$records
Measure.Caravan.5.auto$records
Measure.wine.origin=Measure(wine,wine,target="Class")
Measure.wine.7.smote=Measure(smote.wine.7,wine,target="Class")
Measure.wine.7.ROSE=Measure(rose.wine.7,wine,target="Class")
Measure.wine.7.GANs=Measure(GANs.wine.7,wine,target="Class")
Measure.wine.7.auto=Measure(auto.wine.7,wine,target="Class")
Measure.wine.origin$records
Measure.wine.7.smote$records
Measure.wine.7.ROSE$records
Measure.wine.7.GANs$records
Measure.wine.7.auto$records
Measure.banking.origin=Measure(banking,banking,target="Class")
Measure.banking.7.smote=Measure(smote.banking.7,banking,target="Class")
Measure.banking.7.ROSE=Measure(rose.banking.7,banking,target="Class")
Measure.banking.7.GANs=Measure(GANs.banking.7,banking,target="Class")
Measure.banking.7.auto=Measure(auto.banking.7,banking,target="Class")
Measure.banking.origin$records
Measure.banking.7.smote$records
Measure.banking.7.ROSE$records
Measure.banking.7.GANs$records
Measure.banking.7.auto$records
Measure.abalone.origin=Measure(abalone,abalone,target="Class")
Measure.abalone.7.smote=Measure(smote.abalone.7,abalone,target="Class")
Measure.abalone.7.ROSE=Measure(rose.abalone.7,abalone,target="Class")
Measure.abalone.7.GANs=Measure(GANs.abalone.7,abalone,target="Class")
Measure.abalone.7.GANs.2=Measure(GANs.abalone.7.2,abalone,target="Class")
Measure.abalone.7.auto=Measure(auto.abalone.7,abalone,target="Class")
Measure.abalone.origin$records
aa=Measure.abalone.7.smote$records
Measure.abalone.7.ROSE$records
Measure.abalone.7.GANs$records
Measure.abalone.7.GANs.2$records
Measure.abalone.7.auto$records
Measure.Caravan.origin=Measure(Caravan,Caravan,target="Class")
Measure.Caravan.7.smote=Measure(smote.Caravan.7,Caravan,target="Class")
Measure.Caravan.7.ROSE=Measure(rose.Caravan.7,Caravan,target="Class")
Measure.Caravan.7.GANs=Measure(GANs.Caravan.7,Caravan,target="Class")
Measure.Caravan.7.auto=Measure(auto.Caravan.7,Caravan,target="Class")
Measure.Caravan.origin$records
Measure.Caravan.7.smote$records
Measure.Caravan.7.ROSE$records
Measure.Caravan.7.GANs$records
Measure.Caravan.7.auto$records

Measure.abalone.b.smote=Measure(smote.abalone.b,abalone,target="Class")
Measure.abalone.b.GANs=Measure(GANs.abalone.b,abalone,target="Class")
Measure.abalone.b.ROSE=Measure(rose.abalone.b,abalone,target="Class")
Measure.abalone.b.auto=Measure(auto.abalone.b,abalone,target="Class")
Measure.abalone.b.smote$records
Measure.abalone.b.GANs$records
Measure.abalone.b.ROSE$records
Measure.abalone.b.auto$records

Measure.Caravan.b.smote=Measure(smote.Caravan.b,Caravan,target="Class")
Measure.Caravan.b.GANs=Measure(GANs.Caravan.b,Caravan,target="Class")
Measure.Caravan.b.ROSE=Measure(rose.Caravan.b,Caravan,target="Class")
Measure.Caravan.b.auto=Measure(auto.Caravan.b,Caravan,target="Class")
Measure.Caravan.b.smote$records
Measure.Caravan.b.GANs$records
Measure.Caravan.b.ROSE$records
Measure.Caravan.b.auto$records

Measure.wine.b.smote=Measure(smote.wine.b,wine,target="Class")
Measure.wine.b.GANs=Measure(GANs.wine.b,wine,target="Class")
Measure.wine.b.ROSE=Measure(rose.wine.b,wine,target="Class")
Measure.wine.b.auto=Measure(auto.wine.b,wine,target="Class")
Measure.wine.b.smote$records
Measure.wine.b.GANs$records
Measure.wine.b.ROSE$records
Measure.wine.b.auto$records

Measure.banking.b.smote=Measure(smote.banking.b,banking,target="Class")
Measure.banking.b.GANs=Measure(GANs.banking.b,banking,target="Class")
Measure.banking.b.ROSE=Measure(rose.banking.b,banking,target="Class")
Measure.banking.b.auto=Measure(auto.banking.b,banking,target="Class")
Measure.banking.b.smote$records
Measure.banking.b.GANs$records
Measure.banking.b.ROSE$records
Measure.banking.b.auto$records
